[build.environment]
HUGO_VERSION = "0.128.0"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.deploy-preview]
command = "hugo --minify -D -F -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --minify --gc -b $DEPLOY_PRIME_URL"
